### ISSUE TITLE
Feature engineering  

### ISSUE THREAD

**Issue by adarsh-dattatri** [Predicon/exploration-notebooks#7]
add Lender names   
Number of transaction days   
Make a document of features by data source

**Comment by vishal-subedi** [comment]
- dti_percentage
- pay_day_test_result_amount(Confirm with Syed and Dan as to what this feature actually represents)
- is_pds_history_found
- in1_is_direct_deposite(check the pps score after making the null strings as another category)

**Comment by adarsh-dattatri** [comment]
time at employer

**Comment by adarsh-dattatri** [comment]
(positive days - negative days)
% of positive days

**Comment by adarsh-dattatri** [comment]
Add PPS scores and dependence measures for current features

**Comment by adarsh-dattatri** [comment]
Cash & ATM
